// GENERATED FILE — do not edit by hand.
// Source of truth: docs/content-matrix.csv (cluster_proposed, matrix_pillar_proposed).
// Refresh with: node scripts/build-article-clusters.cjs

export interface ArticleClusterEntry {
  /** Normalised cluster: playbook clusters (baseline, efficiency, circular-economy,
   * resilience, regenerative), tool clusters (biofuels, ecolabel, vsme),
   * candidate clusters (no tool/playbook yet), "pillar", or "none". */
  cluster: string;
  /** First proposed pillar for the top back-link, or null (-> /articles). */
  pillarSlug: string | null;
}

export const ARTICLE_CLUSTERS: Record<string, ArticleClusterEntry> = {
  "advanced-biofuels": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "advantages-and-disadvantages-of-ecolabels": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "advantages-disadvantages-agribusiness": { cluster: "agribusiness-strategy", pillarSlug: "agribusiness-guide" },
  "advantages-disadvantages-intercropping": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "agribusiness-guide": { cluster: "pillar", pillarSlug: null },
  "agribusiness-supply-chain-explained": { cluster: "agribusiness-strategy", pillarSlug: "agribusiness-guide" },
  "agribusiness-technology-trends": { cluster: "agribusiness-strategy", pillarSlug: "agribusiness-guide" },
  "agricultural-drainage": { cluster: "efficiency", pillarSlug: "water-management-guide" },
  "agricultural-irrigation": { cluster: "efficiency", pillarSlug: "water-management-guide" },
  "agricultural-sustainability-checklist": { cluster: "baseline", pillarSlug: "csrd-esg-guide" },
  "agriculture-vs-agribusiness": { cluster: "agribusiness-strategy", pillarSlug: "agribusiness-guide" },
  "agroforestry-economics": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "biochar-soil-amendment": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "biodiversity-assessment-farms": { cluster: "biodiversity", pillarSlug: null },
  "biodiversity-guide": { cluster: "biodiversity", pillarSlug: null },
  "biodiversity-net-gain-agriculture": { cluster: "biodiversity", pillarSlug: null },
  "biofuel-sustainability-ranking": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "biofuel-trends-2025": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "biofuels-explained": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "biofuels-guide": { cluster: "pillar", pillarSlug: null },
  "biofuels-in-aviation": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "biomass-energy-farm": { cluster: "biofuels", pillarSlug: "circular-economy-guide" },
  "building-baseline": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "building-esg-response-system": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "buyer-scope-3-request": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "buyer-scrutiny": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "carbon-markets-agriculture": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "cellulosic-biofuels": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "cellulosic-vs-traditional-biofuels": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "challenges-to-ecolabels": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "circular-economy-explained": { cluster: "circular-economy", pillarSlug: "circular-economy-guide" },
  "circular-economy-guide": { cluster: "pillar", pillarSlug: null },
  "circular-supply-chains-food": { cluster: "circular-economy", pillarSlug: "circular-economy-guide" },
  "climate-risk-assessment-farms": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "closed-loop-nutrient-cycling": { cluster: "efficiency", pillarSlug: "circular-economy-guide" },
  "companion-planting-introduction": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "composting-nutrient-cycling-roi": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "controlled-drainage": { cluster: "efficiency", pillarSlug: null },
  "cooperative-models-small-farms": { cluster: "resilience", pillarSlug: "small-farm-guide" },
  "cover-crop-selection-guide": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "cover-crop-termination": { cluster: "regenerative", pillarSlug: null },
  "cover-crops-roi": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "crop-diversification-risk": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "csrd-esg-guide": { cluster: "pillar", pillarSlug: "vsme-guide" },
  "csrd-vsme-agricultural-suppliers": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "direct-marketing-small-farms": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
  "disadvantages-of-ecolabels": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "drivers-of-ecolabel-adoption": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "drought-resilience-water-management": { cluster: "resilience", pillarSlug: "water-management-guide" },
  "ecolabel-guide": { cluster: "pillar", pillarSlug: "vsme-guide" },
  "erosion-control-strategies": { cluster: "regenerative", pillarSlug: "soil-management-guide" },
  "esg-competitive-advantage": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "esg-labels-in-2025": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "esg-reporting-small-farms": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "farm-insurance-climate-adaptation": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "farm-succession-planning": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "farm-waste-to-value": { cluster: "circular-economy", pillarSlug: "circular-economy-guide" },
  "financial-resilience-farm-operations": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "first-esg-questionnaire": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "food-deserts-market-opportunity": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
  "globalg-a-p-audit-preparation-guide": { cluster: "ecolabel", pillarSlug: null },
  "globalg-a-p-certification-costs": { cluster: "ecolabel", pillarSlug: null },
  "globalg-a-p-certification-what-sme-farms-need": { cluster: "ecolabel", pillarSlug: "vsme-guide" },
  "globalg-a-p-grasp-worker-welfare": { cluster: "ecolabel", pillarSlug: "vsme-guide" },
  "globalg-a-p-vs-organic-certification": { cluster: "ecolabel", pillarSlug: null },
  "hedgerow-management-economics": { cluster: "biodiversity", pillarSlug: null },
  "how-to-spot-fake-ecolabels": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "industrial-food-system-small-farms": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
  "intercropping-cereal-legume": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "intercropping-climate-resilience": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "intercropping-guide": { cluster: "pillar", pillarSlug: null },
  "intercropping-organic-systems": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "intercropping-pest-management": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "intercropping-practices": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "intercropping-vs-polyculture": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "introduction-to-intercropping": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "irrigation-system-planning": { cluster: "efficiency", pillarSlug: "water-management-guide" },
  "land-use-planning-farms": { cluster: "land-use-planning", pillarSlug: "soil-management-guide" },
  "life-cycle-assessment-explained": { cluster: "baseline", pillarSlug: "circular-economy-guide" },
  "lose-buyers-without-esg": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "market-volatility-strategies": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "measuring-intercropping-effectiveness": { cluster: "intercropping", pillarSlug: "intercropping-guide" },
  "missing-esg-data": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "most-trustworthy-ecolabels": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "nutrient-management-planning": { cluster: "efficiency", pillarSlug: "soil-management-guide" },
  "origins-history-agribusiness": { cluster: "agribusiness-strategy", pillarSlug: "agribusiness-guide" },
  "pest-disease-climate-change": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "pollinator-habitat-farm": { cluster: "biodiversity", pillarSlug: null },
  "precision-irrigation-technology": { cluster: "efficiency", pillarSlug: "water-management-guide" },
  "pros-and-cons-of-advanced-biofuels": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "rainwater-harvesting-agriculture": { cluster: "efficiency", pillarSlug: "water-management-guide" },
  "ranking-biofuel-sustainability": { cluster: "biofuels", pillarSlug: "biofuels-guide" },
  "regenerative-agriculture-economics": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "regenerative-guide": { cluster: "pillar", pillarSlug: null },
  "regenerative-practices-2025": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "regenerative-transition-costs": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "resilience-guide": { cluster: "pillar", pillarSlug: null },
  "scope-1-2-3-agriculture": { cluster: "vsme", pillarSlug: "csrd-esg-guide" },
  "selling-crop-residues-biofuel-feedstock": { cluster: "biofuels", pillarSlug: null },
  "small-farm-competitive-strategy": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
  "small-farm-financial-planning": { cluster: "resilience", pillarSlug: "small-farm-guide" },
  "small-farm-guide": { cluster: "pillar", pillarSlug: null },
  "small-farm-market-channels": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
  "small-farm-value-added-products": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
  "small-vs-large-agribusiness": { cluster: "agribusiness-strategy", pillarSlug: "agribusiness-guide" },
  "soil-compaction-management": { cluster: "efficiency", pillarSlug: "soil-management-guide" },
  "soil-health-business-case": { cluster: "regenerative", pillarSlug: "regenerative-guide" },
  "soil-management-guide": { cluster: "pillar", pillarSlug: null },
  "soil-organic-matter-building": { cluster: "regenerative", pillarSlug: "soil-management-guide" },
  "soil-testing-guide": { cluster: "baseline", pillarSlug: "soil-management-guide" },
  "subsurface-drainage-design": { cluster: "efficiency", pillarSlug: "water-management-guide" },
  "supply-chain-resilience-agriculture": { cluster: "resilience", pillarSlug: "resilience-guide" },
  "sustainability-in-agribusiness": { cluster: "efficiency", pillarSlug: "agribusiness-guide" },
  "the-different-types-of-ecolabels": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "tillage-systems-compared": { cluster: "efficiency", pillarSlug: "soil-management-guide" },
  "value-chains-economic-efficiency": { cluster: "efficiency", pillarSlug: "circular-economy-guide" },
  "vsme-basic-module-explained": { cluster: "vsme", pillarSlug: "vsme-guide" },
  "vsme-buyer-questionnaire-response": { cluster: "vsme", pillarSlug: "vsme-guide" },
  "vsme-five-stacks-mapping": { cluster: "vsme", pillarSlug: "vsme-guide" },
  "vsme-guide": { cluster: "pillar", pillarSlug: null },
  "vsme-vs-full-esrs": { cluster: "vsme", pillarSlug: "vsme-guide" },
  "water-management-guide": { cluster: "pillar", pillarSlug: null },
  "water-quality-management-farms": { cluster: "efficiency", pillarSlug: "water-management-guide" },
  "water-recycling-efficiency": { cluster: "efficiency", pillarSlug: "circular-economy-guide" },
  "what-are-ecolabels": { cluster: "ecolabel", pillarSlug: "ecolabel-guide" },
  "what-are-small-farms": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
  "what-gets-measured": { cluster: "baseline", pillarSlug: "csrd-esg-guide" },
  "what-is-agribusiness": { cluster: "agribusiness-strategy", pillarSlug: "agribusiness-guide" },
  "why-consumers-want-local-food": { cluster: "small-farm-strategy", pillarSlug: "small-farm-guide" },
};

export function getArticleCluster(slug: string): ArticleClusterEntry {
  return ARTICLE_CLUSTERS[slug] ?? { cluster: "none", pillarSlug: null };
}
