/**
 * WordPress → Next.js redirect map
 *
 * Generated from ecosystemsunited.com sitemap (156 posts).
 * Three categories:
 *   - MATCHED: direct topic equivalent (permanent 301)
 *   - CLOSE MATCH: best available topically-related article (permanent 301)
 *   - NO MATCH: no equivalent content, redirect to /articles index (temporary 302)
 */

type Redirect = {
  source: string;
  destination: string;
  permanent: boolean;
};

export const wordpressRedirects: Redirect[] = [
  // === MATCHED REDIRECTS (53 entries) ===
  { source: '/the-advantages-and-disadvantages-of-ecolabels', destination: '/articles/advantages-and-disadvantages-of-ecolabels', permanent: true },
  { source: '/the-economics-of-regenerative-agriculture', destination: '/articles/regenerative-agriculture-economics', permanent: true },
  { source: '/reason-and-benefits-of-agricultural-drainage', destination: '/articles/agricultural-drainage', permanent: true },
  { source: '/so-you-want-an-irrigation-system', destination: '/articles/irrigation-system-planning', permanent: true },
  { source: '/agricultural-irrigation', destination: '/articles/agricultural-irrigation', permanent: true },
  { source: '/biofuels-explained', destination: '/articles/biofuels-explained', permanent: true },
  { source: '/an-introduction-to-intercropping', destination: '/articles/introduction-to-intercropping', permanent: true },
  { source: '/advantages-and-disadvantages-of-intercropping', destination: '/articles/advantages-disadvantages-intercropping', permanent: true },
  { source: '/intercropping-practices', destination: '/articles/intercropping-practices', permanent: true },
  { source: '/intercropping-in-organic-agricultural-systems', destination: '/articles/intercropping-organic-systems', permanent: true },
  { source: '/an-introduction-to-companion-planting', destination: '/articles/companion-planting-introduction', permanent: true },
  { source: '/measuring-the-effectiveness-of-intercropping', destination: '/articles/measuring-intercropping-effectiveness', permanent: true },
  { source: '/what-value-chains-are-and-how-they-can-optimize-economic-efficiency', destination: '/articles/value-chains-economic-efficiency', permanent: true },
  { source: '/question-what-are-small-farms-how-do-they-contribute-to-society-and-what-struggles-are-they-faced-with', destination: '/articles/what-are-small-farms', permanent: true },
  { source: '/question-what-strategies-can-small-farmers-use-to-better-compete-in-a-challenging-market-environment', destination: '/articles/small-farm-competitive-strategy', permanent: true },
  { source: '/7-tips-for-the-successful-implementation-of-direct-marketing-strategies-by-small-farmers', destination: '/articles/direct-marketing-small-farms', permanent: true },
  { source: '/the-circular-economy-explained', destination: '/articles/circular-economy-explained', permanent: true },
  { source: '/what-is-a-life-cycle-assessment-what-the-different-parts-of-a-life-cycle-assessment', destination: '/articles/life-cycle-assessment-explained', permanent: true },
  { source: '/7-biofuel-trends-to-expect-in-2025', destination: '/articles/biofuel-trends-2025', permanent: true },
  { source: '/the-different-types-of-ecolabels', destination: '/articles/the-different-types-of-ecolabels', permanent: true },
  { source: '/what-are-ecolabels', destination: '/articles/what-are-ecolabels', permanent: true },
  { source: '/the-disadvantages-of-ecolabels', destination: '/articles/disadvantages-of-ecolabels', permanent: true },
  { source: '/challenges-to-ecolabels', destination: '/articles/challenges-to-ecolabels', permanent: true },
  { source: '/drivers-of-ecolabel-adoption-what-factors-lead-to-ecolabel-uptake-and-acceptance', destination: '/articles/drivers-of-ecolabel-adoption', permanent: true },
  { source: '/esg-labels-in-2025', destination: '/articles/esg-labels-in-2025', permanent: true },
  { source: '/are-you-being-greenwashed-how-to-spot-fake-ecolabels', destination: '/articles/how-to-spot-fake-ecolabels', permanent: true },
  { source: '/most-trustworthy-ecolabels', destination: '/articles/most-trustworthy-ecolabels', permanent: true },
  { source: '/cellulosic-biofuels-explained', destination: '/articles/cellulosic-biofuels', permanent: true },
  { source: '/ranking-the-sustainability-of-biofuels', destination: '/articles/ranking-biofuel-sustainability', permanent: true },
  { source: '/what-are-advanced-biofuels', destination: '/articles/advanced-biofuels', permanent: true },
  { source: '/the-pros-and-cons-of-advanced-biofuels', destination: '/articles/pros-and-cons-of-advanced-biofuels', permanent: true },
  { source: '/cellulosic-ethanol-vs-traditional-biofuels', destination: '/articles/cellulosic-vs-traditional-biofuels', permanent: true },
  { source: '/biofuels-in-the-aviation-industry-5-trends', destination: '/articles/biofuels-in-aviation', permanent: true },
  { source: '/sustainability-in-agribusiness-how-smart-practices-drive-long-term-profitability', destination: '/articles/sustainability-in-agribusiness', permanent: true },
  { source: '/small-vs-large-agribusiness', destination: '/articles/small-vs-large-agribusiness', permanent: true },
  { source: '/the-origins-and-history-of-agribusiness', destination: '/articles/origins-history-agribusiness', permanent: true },
  { source: '/what-is-agribusiness-how-did-agribusiness-evolve', destination: '/articles/what-is-agribusiness', permanent: true },
  { source: '/what-is-agribusiness-what-are-the-different-parts-of-agribusiness', destination: '/articles/what-is-agribusiness', permanent: true },
  { source: '/advantages-and-disadvantages-of-agribusiness', destination: '/articles/advantages-disadvantages-agribusiness', permanent: true },
  { source: '/differences-between-agriculture-and-agribusiness', destination: '/articles/agriculture-vs-agribusiness', permanent: true },
  { source: '/intercropping-vs-polyculture-how-multi-crop-systems-boost-farm-sustainability', destination: '/articles/intercropping-vs-polyculture', permanent: true },
  { source: '/cover-crop-seeds-for-soil-regeneration', destination: '/articles/cover-crops-roi', permanent: true },
  { source: '/7-breakthrough-regenerative-agricultural-practices-transforming-food-systems-in-2025', destination: '/articles/regenerative-practices-2025', permanent: true },
  { source: '/are-advanced-biofuels-the-future-of-energy', destination: '/articles/advanced-biofuels', permanent: true },
  { source: '/sustainable-aviation-fuel-investments', destination: '/articles/biofuels-in-aviation', permanent: true },
  { source: '/soil-health-the-foundation-of-sustainable-agriculture', destination: '/articles/soil-health-business-case', permanent: true },
  { source: '/ai-powered-precision-cover-cropping-the-future-of-soil-health-management', destination: '/articles/cover-crop-selection-guide', permanent: true },
  { source: '/food-deserts', destination: '/articles/food-deserts-market-opportunity', permanent: true },
  { source: '/the-industrialization-of-the-food-system', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/a-food-systems-approach', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/the-food-systems-approach', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-biochar', destination: '/articles/biochar-soil-amendment', permanent: true },
  { source: '/co-operatives', destination: '/articles/cooperative-models-small-farms', permanent: true },

  // === CLOSE MATCH REDIRECTS (60 entries) ===
  { source: '/soil-microbial-health-checklist', destination: '/articles/soil-testing-guide', permanent: true },
  { source: '/stackable-sustainability-in-agriculture-a-practical-path-to-regenerative-farming', destination: '/articles/regenerative-agriculture-economics', permanent: true },
  { source: '/small-farm-economic-advantage-implementing-the-stackable-sustainability-pyramid-framework', destination: '/articles/small-farm-competitive-strategy', permanent: true },
  { source: '/precipitation', destination: '/articles/rainwater-harvesting-agriculture', permanent: true },
  { source: '/hydrology-101', destination: '/articles/water-quality-management-farms', permanent: true },
  { source: '/eutrophication-choking-the-life-out-of-a-body-of-water-near-you', destination: '/articles/water-quality-management-farms', permanent: true },
  { source: '/buffer-zones-buffer-strips-what-they-are-and-why-we-need-them', destination: '/articles/erosion-control-strategies', permanent: true },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-afforestation', destination: '/articles/agroforestry-economics', permanent: true },
  { source: '/all-about-urbanization', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/the-importance-of-agriculture-and-how-it-has-evolved-throughout-the-past-century', destination: '/articles/what-is-agribusiness', permanent: true },
  { source: '/sustainable-agriculture-defined-and-discussed', destination: '/articles/agricultural-sustainability-checklist', permanent: true },
  { source: '/industrial-agriculture-described-a-comparison-of-the-benefits-and-disadvantages', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/community-gardens', destination: '/articles/cooperative-models-small-farms', permanent: true },
  { source: '/community-supported-agriculture-csa-defined-and-described-the-challenges-opportunities-they-provide', destination: '/articles/small-farm-market-channels', permanent: true },
  { source: '/the-15-principles-of-organic-farming', destination: '/articles/regenerative-practices-2025', permanent: true },
  { source: '/crop-quality-when-better-is-better', destination: '/articles/soil-health-business-case', permanent: true },
  { source: '/the-most-common-plant-defects-and-their-causes', destination: '/articles/pest-disease-climate-change', permanent: true },
  { source: '/10-common-plant-disease-symptoms', destination: '/articles/pest-disease-climate-change', permanent: true },
  { source: '/different-types-of-plant-resistance', destination: '/articles/pest-disease-climate-change', permanent: true },
  { source: '/a-brief-introduction-to-plant-diseases', destination: '/articles/pest-disease-climate-change', permanent: true },
  { source: '/question-what-is-the-difference-between-plant-resistance-and-plant-tolerance', destination: '/articles/pest-disease-climate-change', permanent: true },
  { source: '/what-is-plant-tolerance-why-is-plant-tolerance-important', destination: '/articles/pest-disease-climate-change', permanent: true },
  { source: '/an-introduction-integrated-pest-management-ipm', destination: '/articles/intercropping-pest-management', permanent: true },
  { source: '/biological-control-via-entomophatogenic-viruses-baculovirus', destination: '/articles/intercropping-pest-management', permanent: true },
  { source: '/biological-controls-in-horticulture-and-agriculture-defined-and-explained', destination: '/articles/intercropping-pest-management', permanent: true },
  { source: '/crop-wild-relatives-what-they-are-and-why-they-are-important', destination: '/articles/biodiversity-assessment-farms', permanent: true },
  { source: '/the-importance-of-annual-grasses', destination: '/articles/cover-crop-selection-guide', permanent: true },
  { source: '/5-reasons-not-to-buy-hybrid-seeds', destination: '/articles/cover-crop-selection-guide', permanent: true },
  { source: '/bioregional-seed-banking-networks-preserving-agricultural-heritage-for-a-resilient-future', destination: '/articles/biodiversity-assessment-farms', permanent: true },
  { source: '/difference-between-intensive-and-extensive-agriculture', destination: '/articles/what-is-agribusiness', permanent: true },
  { source: '/the-dangers-of-industrial-agriculture', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/factory-farming-and-human-health', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/air-pollution-by-concentrated-animal-feeding-operations', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/the-historical-development-of-organic-farming', destination: '/articles/regenerative-practices-2025', permanent: true },
  { source: '/the-food-pyramid-a-brief-history', destination: '/articles/industrial-food-system-small-farms', permanent: true },
  { source: '/why-is-interest-in-the-alternative-food-movement-growing', destination: '/articles/why-consumers-want-local-food', permanent: true },
  { source: '/the-main-challenges-to-alternative-food-networks', destination: '/articles/small-farm-market-channels', permanent: true },
  { source: '/alternative-food-networks-and-new-peasantry', destination: '/articles/small-farm-market-channels', permanent: true },
  { source: '/what-is-ethanol', destination: '/articles/biofuels-explained', permanent: true },
  { source: '/ethanol-explained-a-deep-dive-into-its-market-impacts-and-innovations', destination: '/articles/biofuels-explained', permanent: true },
  { source: '/the-ethanol-debate-a-closer-look-at-the-pros-and-cons', destination: '/articles/pros-and-cons-of-advanced-biofuels', permanent: true },
  { source: '/a-vision-for-renewable-energy-the-forgotten-story-of-henry-ford-and-ethanol', destination: '/articles/biofuels-explained', permanent: true },
  { source: '/ultimate-guide-to-biofuels', destination: '/articles/biofuels-explained', permanent: true },
  { source: '/beginners-guide-to-investing-in-biofuels', destination: '/articles/biofuel-sustainability-ranking', permanent: true },
  { source: '/renewable-diesel-vs-biodiesel', destination: '/articles/cellulosic-vs-traditional-biofuels', permanent: true },
  { source: '/companies-leading-in-cellulosic-biofuels', destination: '/articles/cellulosic-biofuels', permanent: true },
  { source: '/whos-leading-the-advanced-biofuel-industry', destination: '/articles/advanced-biofuels', permanent: true },
  { source: '/lignocellulosic-ethanol-the-future-of-sustainable-biofuels', destination: '/articles/cellulosic-biofuels', permanent: true },
  { source: '/how-perennial-grain-systems-are-transforming-agriculture', destination: '/articles/regenerative-practices-2025', permanent: true },
  { source: '/the-difference-between-intercropping-and-companion-planting', destination: '/articles/intercropping-vs-polyculture', permanent: true },
  { source: '/companion-planting-fact-or-folklore', destination: '/articles/companion-planting-introduction', permanent: true },
  { source: '/soil-sealing-what-it-is-and-why-it-is-important', destination: '/articles/soil-compaction-management', permanent: true },
  { source: '/livestock-fact-or-prejudice', destination: '/articles/agricultural-sustainability-checklist', permanent: true },
  { source: '/incentives-and-labeling-in-marine-environments', destination: '/articles/what-are-ecolabels', permanent: true },
  { source: '/a-history-of-agricultural-education-in-the-united-states', destination: '/articles/what-is-agribusiness', permanent: true },
  { source: '/a-history-of-domestic-american-agricultural-policy', destination: '/articles/what-is-agribusiness', permanent: true },
  { source: '/what-are-open-source-seeds-why-are-open-source-seeds-important', destination: '/articles/biodiversity-assessment-farms', permanent: true },
  { source: '/what-does-it-mean-to-be-open-source-why-is-interest-in-open-source-licensing-growing', destination: '/articles/biodiversity-assessment-farms', permanent: true },
  { source: '/review-and-analysis-of-of-the-benefits-purposes-and-motivations-associated-with-community-gardens-in-the-united-states', destination: '/articles/cooperative-models-small-farms', permanent: true },
  { source: '/the-influence-of-social-involvment-neighborhood-aesthetics-and-community-garden-participation-on-fruit-and-vegetable-conspumption', destination: '/articles/cooperative-models-small-farms', permanent: true },

  // === NO MATCH — redirect to articles index (79 entries) ===
  { source: '/question-how-can-transport-systems-be-redesigned-to-improve-energy-efficiency', destination: '/articles', permanent: false },
  { source: '/smart-electric-grids', destination: '/articles', permanent: false },
  { source: '/question-what-are-the-main-sources-of-energy-in-the-world-why-do-fossil-fuels-still-dominate-our-energy-use', destination: '/articles', permanent: false },
  { source: '/249-2', destination: '/articles', permanent: false },
  { source: '/moose', destination: '/articles', permanent: false },
  { source: '/how-is-a-beautiful-lawn-the-perfect-antithesis-of-an-ecological-system', destination: '/articles', permanent: false },
  { source: '/the-benefits-of-fire', destination: '/articles', permanent: false },
  { source: '/question-what-is-meant-by-strong-sustainability', destination: '/articles', permanent: false },
  { source: '/question-is-there-such-thing-as-a-human-carrying-capacity', destination: '/articles', permanent: false },
  { source: '/plant-breeding-and-selection-a-never-ending-story', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-albedo-enhancement', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-advantages-and-disadvantages-of-ambient-air-capture', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-ocean-fertilization', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-space-reflectors', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-stratospheric-aerosols', destination: '/articles', permanent: false },
  { source: '/what-is-geoengineering', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-bioenergy-with-carbon-capture-and-sequestration', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-ocean-alkalinity-enhancement', destination: '/articles', permanent: false },
  { source: '/geoengineering-explained-the-benefits-and-challenges-of-enhanced-weathering', destination: '/articles', permanent: false },
  { source: '/5-ways-that-humans-impact-ecosystems', destination: '/articles', permanent: false },
  { source: '/ecology-defined-a-description-of-the-components-of-an-ecosystem', destination: '/articles', permanent: false },
  { source: '/environmental-management-defined', destination: '/articles', permanent: false },
  { source: '/shaping-sustainable-cities-the-intersection-of-urban-planning-and-energy-consumption', destination: '/articles', permanent: false },
  { source: '/the-green-revolution', destination: '/articles', permanent: false },
  { source: '/the-difference-between-z-farming-zero-acreage-and-urban-agriculture', destination: '/articles', permanent: false },
  { source: '/question-what-is-urban-agriculture-and-how-does-it-impact-urban-communities', destination: '/articles', permanent: false },
  { source: '/question-what-does-organic-really-mean', destination: '/articles', permanent: false },
  { source: '/vertical-farming-when-high-tech-meets-food-production', destination: '/articles', permanent: false },
  { source: '/zero-acreage-farming-zfarming-what-it-is-and-how-it-can-change-the-future-of-urban-agriculture', destination: '/articles', permanent: false },
  { source: '/a-concise-description-of-biotechnology', destination: '/articles', permanent: false },
  { source: '/the-benefits-of-urban-agriculture', destination: '/articles', permanent: false },
  { source: '/the-disadvantages-associated-with-urban-agriculture', destination: '/articles', permanent: false },
  { source: '/challenges-to-urban-agriculture', destination: '/articles', permanent: false },
  { source: '/question-what-is-horticulture', destination: '/articles', permanent: false },
  { source: '/horticulture', destination: '/articles', permanent: false },
  { source: '/the-benefits-and-problems-associated-with-aquaculture', destination: '/articles', permanent: false },
  { source: '/question-what-is-aquaculture-and-why-is-it-important', destination: '/articles', permanent: false },
  { source: '/defining-aquaculture-and-its-role-in-the-food-production-system', destination: '/articles', permanent: false },
  { source: '/what-are-smart-cities-how-can-smart-cities-improve-the-lives-of-citizens', destination: '/articles', permanent: false },
  { source: '/question-what-kind-of-services-does-nature-produce', destination: '/articles', permanent: false },
  { source: '/question-how-can-the-use-of-materials-be-reduced-and-what-industries-may-benefit-the-most-from-the-increased-efficiency', destination: '/articles', permanent: false },
  { source: '/an-alternative-to-the-gdp', destination: '/articles', permanent: false },
  { source: '/business-clusters-what-they-are-and-why-they-provide-a-competitive-advantage', destination: '/articles', permanent: false },
  { source: '/institutions-what-they-are-why-we-need-them-and-how-they-shape-our-everyday-lives', destination: '/articles', permanent: false },
  { source: '/the-principal-agent-problem-what-it-is-why-its-important-and-how-it-can-be-solved', destination: '/articles', permanent: false },
  { source: '/question-what-are-networks-and-how-are-they-classified', destination: '/articles', permanent: false },
  { source: '/electric-vehicle-deep-dive', destination: '/articles', permanent: false },
  { source: '/the-dangers-of-dependence-on-big-tech-in-electric-vehicles-a-risky-road-ahead', destination: '/articles', permanent: false },
  { source: '/the-giants-of-electric-vehicles-challenges-of-a-dominated-market', destination: '/articles', permanent: false },
  { source: '/5-innovative-ev-companies-to-support-in-2025', destination: '/articles', permanent: false },
  { source: '/can-our-power-grid-handle-electric-vehicles', destination: '/articles', permanent: false },
  { source: '/are-ev-batteries-worse-than-gasoline', destination: '/articles', permanent: false },
  { source: '/are-hydrogen-fuel-cells-safer', destination: '/articles', permanent: false },
  { source: '/real-alternatives-to-electric-vehicles', destination: '/articles', permanent: false },
  { source: '/a-brief-history-of-development-for-poverty-reduction', destination: '/articles', permanent: false },
  { source: '/networks-in-theory', destination: '/articles', permanent: false },
  { source: '/what-is-social-exclusion', destination: '/articles', permanent: false },
  { source: '/what-is-a-farm-what-are-the-different-tax-structures-for-farms', destination: '/articles', permanent: false },
  { source: '/a-brief-introduction-to-neoliberalism-in-the-united-states', destination: '/articles', permanent: false },
  { source: '/what-is-technoscience-how-has-technoscience-impacted-society', destination: '/articles', permanent: false },
  { source: '/how-have-u-s-tax-policies-turned-farms-into-tax-havens', destination: '/articles', permanent: false },
  { source: '/what-is-social-exclusion-how-has-societys-understanding-of-social-exclusion-evolved', destination: '/articles', permanent: false },
  { source: '/a-history-and-definition-of-corporations', destination: '/articles', permanent: false },
  { source: '/did-neoliberalism-kill-the-family-farm', destination: '/articles', permanent: false },
  { source: '/what-are-oligarchies', destination: '/articles', permanent: false },
  { source: '/the-resurgence-of-oligarchies-how-and-why-theyve-returned', destination: '/articles', permanent: false },
  { source: '/mark-and-delia-owens-the-cry-of-the-kahahari', destination: '/articles', permanent: false },
  { source: '/what-is-co-cultural-communication-why-is-co-cultural-communication-important', destination: '/articles', permanent: false },
  { source: '/what-are-the-main-factors-that-affect-co-cultural-communication-what-are-the-different-co-cultural-communication-strategies', destination: '/articles', permanent: false },
  { source: '/joel-salatin-everything-i-want-to-do-is-illegal', destination: '/articles', permanent: false },
  { source: '/bringing-good-food-to-others-investigating-the-subjects-of-alternative-food-practices', destination: '/articles', permanent: false },
  { source: '/the-social-basis-of-agro-environmental-concern-physical-versus-social-proximity', destination: '/articles', permanent: false },
  { source: '/kill-it-and-eat-it-locavores-give-cities-indigestion', destination: '/articles', permanent: false },
  { source: '/question-how-are-plants-propagated', destination: '/articles', permanent: false },
  { source: '/beginners-guide-to-solar-power-for-house', destination: '/articles', permanent: false },
  { source: '/solar-energy-companies-opportunties-risks-and-the-future-of-green-investing', destination: '/articles', permanent: false },
  { source: '/a-brief-history-of-land-grant-colleges-in-the-united-states', destination: '/articles', permanent: false },
  { source: '/question-what-is-agricultural-extension-what-services-does-it-provide', destination: '/articles', permanent: false },
];
